export const exampleActionTypes = {
	SET_EXAMPLE_STATE: 'SET_EXAMPLE_STATE',
	GET_USERS: 'GET_USERS',
	GET_USERS_FAIL: 'GET_USERS_FAIL',
	GET_ALL_POSTS: 'GET_ALL_POSTS',
	GET_ALL_POSTS_FAIL: 'GET_USERS_FAIL',
	GET_POST_COMMENTS: 'GET_POST_COMMENTS',
};
